<?php $quote = $this->getCheckoutSession()->getQuote(); ?>
<?php $config = $this->getConfig(); ?>

<h2>email</h2>
<fieldset class="fieldset">
    <div class="field name required">
        <label class="label" for="name"><span>Email</span></label>
        <div class="control">
            <input name="email" id="firstname" title="Firstname" value="<?php echo $quote->getCustomerEmail(); ?>" class="input-text" type="text">
        </div>
    </div>
</fieldset>

<h2>address</h2>

    <form action="" id="shipping-address">
        <fieldset class="fieldset">
        <div class="field required">
            <label class="label" for="name"><span>Firstname</span></label>
            <div class="control">
                <input name="firstname" id="firstname" title="Firstname" value="<?php echo $quote->getShippingAddress()->getFirstname(); ?>" class="input-text required-entry" type="text">
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="lastname"><span>Lastname</span></label>
            <div class="control">
                <input name="lastname" id="lastname" title="lastname" value="<?php echo $quote->getShippingAddress()->getLastname(); ?>" class="input-text required-entry" type="text">
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="name"><span>City</span></label>
            <div class="control">
                <input name="city" id="city" title="City" value="<?php echo $quote->getShippingAddress()->getCity(); ?>" class="input-text required-entry" type="text">
            </div>
        </div>
        <div class="field required">
            <label class="label" for="telephone"><span>Telephone</span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="Telephone" value="<?php echo $quote->getShippingAddress()->getTelephone(); ?>" class="input-text required-entry" type="text">
            </div>
        </div>
        <div class="field required">
            <label class="label" for="postcode"><span>Postcode</span></label>
            <div class="control">
                <input name="postcode" id="postcode" title="Postcode" value="<?php echo $quote->getShippingAddress()->getPostcode(); ?>" class="input-text required-entry" type="text">
            </div>
        </div>
        <div class="field required">
            <label class="label" for="name"><span>Street</span></label>
            <div class="control">
                <input name="street" id="firstname" title="Firstname" value="<?php echo $quote->getShippingAddress()->getStreetLine(1); ?>" class="input-text required-entry" type="text">
            </div>
        </div>
        <div class="field required">
            <label class="label" for="name"><span>Countryid</span></label>
            <div class="control">
                <select  name="countryId" id="firstname" title="Firstname" value="<?php echo $quote->getShippingAddress()->getCountryId(); ?>" class="input-text required-entry" type="text">
                <?php foreach($this->getCountries() as $country): ?>
                  <option value="<?php echo $country->getCountryId(); ?>" <?php if($quote->getShippingAddress()->getCountryId() === $country->getCountryId()):?> selected<?php endif; ?>><?php echo $country->getName(); ?></p>
                <?php endforeach; ?>
                </select>
            </div>
        </div>
        <button type="submit">save</button>
        </fieldset>
    </form>

<h2>shipping methods</h2>
<ul>
    <?php foreach($config['activeCarriers'] as $shippingMethod): ?>
        <li><?php echo $shippingMethod;?></li>
    <?php endforeach; ?>
</ul>

<h2>payment methods</h2>
<ul>
    <?php foreach($this->getAvailablePaymentMethods() as $paymentMethod): ?>
        <li><input type="radio" value="<?php echo $paymentMethod->getCode(); ?>"/><?php echo $paymentMethod->getTitle(); ?></li>
    <?php endforeach; ?>
</ul>


<h2>review</h2>
<div id="review">
    <ul>
    <?php foreach($quote->getAllVisibleItems() as $item):?>
        <li><?php echo $item->getName(); ?></li>
    <?php endforeach; ?>
    </ul>
</div>

<button id="place-order" class="action primary">Place Order</button>

<script>
    require(['jquery','mage/validation'], function(){
        //quote, urlBuilder, storage, url, errorProcessor, customer, fullScreenLoader
        //console.log(
            //urlBuilder.createUrl('/guest-carts/:quoteId/payment-information', {quoteId: quote.getQuoteId()})
        //);

        jQuery(document).ready(function(){
            jQuery('#shipping-address').validation().submit(function(){
                var data = {};
                var address = {};
                
                var result = {};
                jQuery.each(jQuery(this).serializeArray(),function(){
                    result[this.name] = this.value;
                });
                result['street'] = [result['street']];
                
                address['shipping_address'] = result;
                address['billing_address'] = result;
                address['shipping_method_code'] = 'flatrate';
                address['shipping_carrier_code'] = 'flatrate';
                
                data['addressInformation'] = address;
                           
                jQuery.ajax({
                  type: "POST",
                  data: JSON.stringify(data),
                  contentType: "application/json; charset=utf-8",                  
                  url: "/rest/default/V1/guest-carts/<?php echo $this->getQuoteIdMask() ?>/shipping-information",
                  dataType: 'json',              
                  success: function(){
                  },
                });
                event.preventDefault();
            });
            
            jQuery('#place-order').click(function(){
                
                var data = {};
                var address = {};
                var payment = {};
                
                var result = {};
                jQuery.each(jQuery('#shipping-address').serializeArray(),function(){
                    result[this.name] = this.value;
                });
                result['street'] = [result['street']];
                
               data['billing_address'] = result;
               data['cartId'] = '<?php echo $this->getQuoteIdMask() ?>';
               data['email'] = 'derrick@experius.nl';
               
               payment['method'] = "checkmo";
               data['paymentMethod'] = payment;
                
               jQuery.ajax({
                  type: "POST",
                  data: JSON.stringify(data),
                  contentType: "application/json; charset=utf-8",                  
                  url: "/rest/default/V1/guest-carts/<?php echo $this->getQuoteIdMask() ?>/payment-information",
                  dataType: 'json',              
                  success: function(response){
                        window.location.replace('/checkout/onepage/success');
                  }
                });
                
            });
            
            
            //rest/default/V1/guest-carts/65b64a1192f5fe4cc9474404668a7cca/payment-information
            
            //{"cartId":"65b64a1192f5fe4cc9474404668a7cca","email":"derrick@experius.nl","paymentMethod":{"method":"checkmo","po_number":null,"additional_data":null},"billingAddress":{"countryId":"NL","regionId":"0","region":"","street":["Voorstraat 82BIS"],"company":"Heesbeen Webservices","telephone":"+31649354289","postcode":"3512 AT","city":"Utrecht","firstname":"Derrick","lastname":"Heesbeen","saveInAddressBook":false}}
            
        
        });
        
    });
</script>

<?php //print_r($this->getConfig()); ?>
<?php //var_dump($this->getQuoteIdMask()); ?>

