<fieldset class="fieldset">
    <form action="" id="shipping-address">
        <div class="field name required">
            <label class="label" for="name"><span>Firstname</span></label>
            <div class="control">
                <input name="firstname" id="firstname" title="Firstname" value="" class="input-text" type="text">
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="name"><span>Lastname</span></label>
            <div class="control">
                <input name="lastname" id="firstname" title="Firstname" value="" class="input-text" type="text">
            </div>
        </div>
        <button type="submit">save</button>
    </form>
</fieldset>


<script>
    require(['jquery'], function(){
        jQuery(document).ready(function(){
            jQuery('#shipping-address').submit(function(){
                var data = {};
                var address = {};
                
                var result = {};
                jQuery.each(jQuery(this).serializeArray(),function(){
                    result[this.name] = this.value;
                });
                
                address['shipping_address'] = result;
                data['addressInformation'] = address;
                console.log(data);
                console.log(JSON.stringify(data));
                jQuery.ajax({
                  type: "POST",
                  //contentType: "application/json; charset=utf-8",
                  url: "/rest/default/V1/guest-carts/<?php echo $this->getQuoteIdMask() ?>/shipping-information<?php //echo $this->getUrl('/rest/default/V1/guest-carts/ba7412783826dfa2aa42bc6375da6138/shipping-information',array('_secure'=>true)); ?>",
                  //data: JSON.stringify(data),
                  contentType: "application/json; charset=utf-8",
                  //data: '{"addressInformation":{"shipping_address":{"countryId":"NL","regionId":"0","region":"","street":["test"],"company":"Test","telephone":"11111111111","postcode":"5571 KB","city":"qweqwe","firstname":"Sam","lastname":"Granger"},"billing_address":{"countryId":"NL","regionId":"0","region":"","street":["test"],"company":"Test","telephone":"11111111111","postcode":"5571 KB","city":"qweqwe","firstname":"Sam","lastname":"Granger","saveInAddressBook":false},"shipping_method_code":"flatrate","shipping_carrier_code":"flatrate"}}',
                  data: '{"addressInformation":{"shipping_address":{"firstname":"","lastname":""}}}',
                  
                  dataType: 'json',              
                  success: function(){
                  },
                });
                event.preventDefault();
            });
        });
        
    });
</script>

<?php var_dump($this->getConfig()); ?>
<?php var_dump($this->getQuoteIdMask()); ?>

